### ISSUE TITLE
Cannot find module 'tailwind-variants' or its corresponding type declarations.

### ISSUE THREAD

**Issue by J4v4Scr1pt** [nextui-org/tailwind-variants#151] opened 2024-01-24 10:44 UTC
Anyone got this error recently?

Just updated to 0.1.20 this appeard:
![image](https://github.com/nextui-org/tailwind-variants/assets/5929055/7c76913c-c8d2-476e-9245-4bce042bfc84)

I can resolve it by pointing to /dist:
![image](https://github.com/nextui-org/tailwind-variants/assets/5929055/66a145e1-048e-40c4-b5a9-981dcbd2a59f)

But that fails my build:
```
[commonjs--resolver] Missing "./dist" specifier in "tailwind-variants" package
error during build:
Error: Missing "./dist" specifier in "tailwind-variants" package
```

What to do here?! 🤷‍♀️

**Comment by mskelton** [comment] 2024-01-25 01:43
@J4v4Scr1pt Can you create a reproduction code sandbox?  This is something I'm not able to reproduce.

**Comment by J4v4Scr1pt** [comment] 2024-01-25 10:34
Hi man!

I tried to create a sandbox but as same as you.. cant reproduce it.. 🤔.

I have locally deleted npm_packages and resinstalled. downgraded tailwind variants to lower versions.
But still same issue, have a nother project and that works. don't know what do do 😅.

**Comment by mskelton** [comment] 2024-01-26 00:59
Hard to say without the specific details of your project. Could be with your TypeScript or bundler config, or with your package manager settings.

I'm going to close this issue since it's not reproducable, but happy to continue the conversation.

**Closed by mskelton** 2024-01-26 00:59 UTC
Labels: bug, cant reproduce
