### ISSUE TITLE
Issues with TypeScript exactOptionalPropertyTypes

### ISSUE THREAD

**Issue by BorisZubchenko** [nextui-org/tailwind-variants#115] opened 2023-10-15 18:38 UTC
**Describe the bug**
When `exactOptionalPropertyTypes` flag enabled, `ts2345` occurs (e.g. ` Type 'undefined' is not assignable to type '"small" | "medium"`).

**To Reproduce**

1. In `tsconfig.json`, set `compilerOptions#exactOptionalPropertyTypes` to true
2. Paste the following code:
```tsx
import { type VariantProps, tv } from 'tailwind-variants'

const variants = tv({
  variants: {
    size: {
      small: '',
      medium: '',
    },
  },
  defaultVariants: {
    size: 'small',
  },
})

type Props = VariantProps<typeof variants>

function Component({ size }: Props) {
  const className = variants({ size })
  return <div className={className}>Component</div>
}
```
3. Receive an error at the `variants({ size })`: `Type 'undefined' is not assignable to type '"small" | "medium"'`

**Expected behavior**
I don't want to receive any error here.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: N/A
- Browser N/A
- Version N/A

**Smartphone (please complete the following information):**

- Device: N/A
- OS: N/A
- Browser N/A
- Version N/A

**Additional context**
- https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes
- https://www.tailwind-variants.org/docs/typescript#extract-variants-from-a-component
```
"tailwind-variants": "0.1.14",
```

**Comment by mskelton** [comment] 2023-10-15 21:54
Duplicate of #97

**Closed by mskelton** 2023-10-15 21:54 UTC
Labels: bug
