### ISSUE TITLE
"Slot variant overrides" does not work to be as expected.

### ISSUE THREAD

**Issue by uknmr** [nextui-org/tailwind-variants#114] opened 2023-10-13 06:09 UTC
```jsx
const slots = tv({
  slots: {
    hoge: {...},
    fuga: 'invisible',
  },
  variants: {
    visible: {
      true: {
        fuga: 'visible',
      },
    },
  },
})

const { fuga } = slots()

return <Component className={fuga({ visible })} />
```

If you write the above, you expect `class="visible"` when `visible === true`. But in reality, it is `class="invisible visible"`.
Is this behavior as intended?

I can work around it by writing the following, but would like to know if there is a better way.

```jsx
const slots = tv({
  slots: {
    hoge: {...},
    fuga: '',
  },
  variants: {
    visible: {
      true: {
        fuga: 'visible',
      },
      false: {
        fuga: 'invisible',
      },
    },
  },
})

const { fuga } = slots()

return <Component className={fuga({ visible })} />
```

**Comment by mskelton** [comment] 2023-10-28 01:19
I'm unable to reproduce this issue. Writing the following test passes correctly.

```
test("test", () => {
  const slots = tv({
    slots: {
      fuga: "invisible",
    },
    variants: {
      visible: {
        true: {
          fuga: "visible",
        },
      },
    },
  });

  const {fuga} = slots();

  expect(fuga()).toBe("invisible");
  expect(fuga({visible: true})).toBe("visible");
});
```

Closing this issue as not-reproducable.

**Closed by mskelton** 2023-10-28 01:19 UTC

**Comment by mskelton** [comment] 2023-10-28 01:20
One thing to check would be the version of tailwind-variants you are using. Slot level variant overrides was added in version 0.1.14
